version: '3'
services:
  mysql_container:
    container_name: mysql_container
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
